---
abstract: 'Add the ability for attributes to remember their history'
author:
  - 'Joel Berger <joel.a.berger@gmail.com>'
build_requires:
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300009, CPAN::Meta::Converter version 2.120351'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-RememberHistory
no_index:
  directory:
    - t
  file:
    - README.pod
requires:
  Moose: 0
  Moose::Exporter: 0
  Moose::Role: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/jberger/MooseX-RememberHistory/issues
  repository: http://github.com/jberger/MooseX-RememberHistory/
version: 0.001
